blueprint:
  name: Zooz ZEN37 Wall Controller Automation Blueprint
  description: |
    Use ZEN37 to control devices.

  domain: automation
  input:
    device_id:
      name: 'Wall controller Device ID (Required)'
      selector:
        device:
          filter:
            - integration: zwave_js
              manufacturer: Zooz
              model: ZEN37
              multiple: false
    button_1_press:
      name: Button 1 Short Press
      description: Action to run on button 1 short press
      default: []
      selector:
        action:
    button_1_hold:
      name: Button 1 Long Press
      description: Action to run on holding (long press) button 1
      default: []
      selector:
        action:
    button_1_press2x:
      name: Button 1 press 2x times
      description: Action to run on double press button 1
      default: []
      selector:
        action:
    button_2_press:
      name: Button 2 Short Press
      description: Action to run on button 2 short press
      default: []
      selector:
        action:
    button_2_hold:
      name: Button 2 Hold
      description: Action to run on holding (long press) button 2
      default: []
      selector:
        action:
    button_2_press2x:
      name: Button 2 press 2x times
      description: Action to run on double press button 2
      default: []
      selector:
        action:
    button_3_press:
      name: Button 3 Short Press
      description: Action to run on button 3 short press
      default: []
      selector:
        action:
    button_3_hold:
      name: Button 3 Hold
      description: Action to run on holding (long press) button 3
      default: []
      selector:
        action:
    button_3_press2x:
      name: Button 3 press 2x times
      description: Action to run on double press button 3
      default: []
      selector:
        action:
    button_4_press:
      name: Button 4 Short Press
      description: Action to run on button 4 short press
      default: []
      selector:
        action:
    button_4_hold:
      name: Button 1 Hold
      description: Action to run on holding (long press) button 4
      default: []
      selector:
        action:
    button_4_press2x:
      name: Button 4 press 2x times
      description: Action to run on double press button 4
      default: []
      selector:
        action:

mode: restart
max_exceeded: silent

trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: !input device_id
      command_class: 91

action:
  - variables:
      target_device_id: !input 'device_id'
      received_device_id: "{{ trigger.event.data.device_id }}"
      received_button: "{{ trigger.event.data.property_key }}"
      received_press: "{{ trigger.event.data.value }}"

  - choose:
      - conditions:
          - "{{ received_device_id == target_device_id}}"
          - "{{ received_button == '001' }}"
          - "{{ received_press == 'KeyPressed' }}"
        sequence: !input button_1_press
      - conditions:
          - "{{ received_device_id == target_device_id}}"
          - "{{ received_button == '001' }}"
          - "{{ received_press == 'KeyHeldDown' }}"
        sequence: !input button_1_hold
      - conditions:
          - "{{ received_device_id == target_device_id}}"
          - "{{ received_button == '001' }}"
          - "{{ received_press == 'KeyPressed2x' }}"
        sequence: !input button_1_press2x

      - conditions:
          - "{{ received_device_id == target_device_id}}"
          - "{{ received_button == '002' }}"
          - "{{ received_press == 'KeyPressed' }}"
        sequence: !input button_2_press
      - conditions:
          - "{{ received_device_id == target_device_id}}"
          - "{{ received_button == '002' }}"
          - "{{ received_press == 'KeyHeldDown' }}"
        sequence: !input button_2_hold
      - conditions:
          - "{{ received_device_id == target_device_id}}"
          - "{{ received_button == '002' }}"
          - "{{ received_press == 'KeyPressed2x' }}"
        sequence: !input button_2_press2x

      - conditions:
          - "{{ received_device_id == target_device_id}}"
          - "{{ received_button == '003' }}"
          - "{{ received_press == 'KeyPressed' }}"
        sequence: !input button_3_press
      - conditions:
          - "{{ received_device_id == target_device_id}}"
          - "{{ received_button == '003' }}"
          - "{{ received_press == 'KeyHeldDown' }}"
        sequence: !input button_3_hold
      - conditions:
          - "{{ received_device_id == target_device_id}}"
          - "{{ received_button == '003' }}"
          - "{{ received_press == 'KeyPressed2x' }}"
        sequence: !input button_3_press2x

      - conditions:
          - "{{ received_device_id == target_device_id}}"
          - "{{ received_button == '004' }}"
          - "{{ received_press == 'KeyPressed' }}"
        sequence: !input button_4_press
      - conditions:
          - "{{ received_device_id == target_device_id}}"
          - "{{ received_button == '004' }}"
          - "{{ received_press == 'KeyHeldDown' }}"
        sequence: !input button_4_hold
      - conditions:
          - "{{ received_device_id == target_device_id}}"
          - "{{ received_button == '004' }}"
          - "{{ received_press == 'KeyPressed2x' }}"
        sequence: !input button_4_press2x
